### ISSUE TITLE
Doesn't use the new version of book. Using cached data which doesn't refresh?

### ISSUE THREAD

**Issue by VictorVow** [duydl/logseq-calibre-metadata#4]
I imported a book using this plugin into Logseq but then realised I hadn't updated it's metadata in Calibre beforehand, so it lacked a synopsis, accurate title, etc. I then updated it's metadata but realised that the plugin doesn't automatically sync the new metadata, so I deleted the Logseq page for this book then tried to re-add it again.

It imported the old version of the book without any of the metadata. I thought that was weird, let me try a couple things:
- Restarting Calibre's content server
- Closing Calibre then reopening it
- Deleting the book from my Calibre library then readding it
- Closing Logseq then reopening it
- Disabling the plugin then re-enabling it

Nada. None of these steps worked in trying to refresh the book data. 

I can see in my browser at http://127.0.0.1:3296 that the updated version of the book is there, but when I use the plugin to add the book to my Logseq it'll always add the old version without the metadata. 

The `Open` button seems to open the old version of the book, and retains the old annotations. I'm not sure how it's able to view them still as those annotations are not present the version of the book now in Calibre. The `Sync` button however does nothing.

**Comment by duydl** [comment]
Instead of using the 127.0.0.1 or localhost, you will not have the problem if using the IP address for the home network. 

![image](https://github.com/duydl/logseq-calibre-metadata/assets/56506156/c1b742eb-e85c-4626-a09f-2f27585f9386)

i.e http://192.168.11.2:8081

**Comment by VictorVow** [comment]
Thanks, that allowed me to add to Logseq some books I added to Calibre yesterday.

However after this I added some more books to Calibre and the plugin was unable to add them. I then tried all the previous test steps and none worked.

I was able to fix this by changing the Content Server Link to http://127.0.0.1:3296. Now whenever I add a book to Calibre I'm able to immediately search to add it into Logseq. Before your reply I was using http://localhost:3296. Thanks for your help.

**Comment by duydl** [comment]
Hi. Glad it works for you now. Btw I think both localhost and 127.0.0.1 (which are kind of the same) didn't work for me. Only 192.168.11.2 IP address did. It could be found by clicking on connect/share on the main menu and is used for all devices to connect to the home network to access the content server.
